### PR TITLE
CIV-4845, fixing CVE suppression

### PR DESCRIPTION
**Pull request by indu2019**
In Spring Cloud OpenFeign 3.0.0 to 3.0.4, 2.2.0.RELEASE to 2.2.9.RELEASE, and older unsupported versions, applications using type-level `@RequestMapping`annotations over Feign client interfaces, can be involuntarily exposing endpoints corresponding to `@RequestMapping`-annotated interface methods.

### JIRA link (if applicable) ###
https://tools.hmcts.net/jira/browse/CIV-4845

### Change description ###
In Spring Cloud OpenFeign 3.0.0 to 3.0.4, 2.2.0.RELEASE to 2.2.9.RELEASE, and older unsupported versions, applications using type-level `@RequestMapping`annotations over Feign client interfaces, can be involuntarily exposing endpoints corresponding to `@RequestMapping`-annotated interface methods.

**Does this PR introduce a breaking change?** (check one with "x")

```
[ ] Yes
[x ] No
```

### CODE REVIEW

**Review by sabahirfan — DISMISSED** [review]

**Review by filippo-possenti-version1 — APPROVED** [review]

**Comment by filippo-possenti-version1** [comment]
Works for me, but why two PRs on the same subject?

https://github.com/hmcts/civil-ccd-definition/pull/1467

**Comment by indu2019** [comment]
> Works for me, but why two PRs on the same subject?
> 
> #1467

I have closed the other PR

**Comment by indu2019** [comment]
closing it because cant run it

**Comment by indu2019** [comment]
reopening it

**Review by sabahirfan — APPROVED** [review]

**Pull request merged**
